[package]
name = "sentiment"
version = "0.1.0"
edition = "2018"

[dependencies]
efflux = "2.0"
vader_sentiment = "0.1.1"

[[bin]]
doc = false
name = "sentiment_mapper"
path = "src/mapper.rs"

[[bin]]
doc = false
name = "sentiment_reducer"
path = "src/reducer.rs"
